# Generated by Django 3.2.6 on 2021-10-04 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso_app', '0002_alter_item_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curse',
            new_name='Course',
        ),
    ]
