# Generated by Django 3.2.6 on 2021-10-04 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso_app', '0003_rename_curse_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='descrip_course', to='curso_app.course'),
        ),
    ]
